-- Seed 500+ quiz questions for La Crêperie des
INSERT INTO public.quiz_questions (question, option_a, option_b, option_c, option_d, correct_answer, category, is_active) VALUES
  ('Quelle est la préfecture du Finistère ?', 'Brest', 'Quimper', 'Rennes', 'Vannes', 'B', 'bretagne', true),
  ('Quel département a pour numéro 35 ?', 'Morbihan', 'Côtes-d''Armor', 'Ille-et-Vilaine', 'Finistère', 'C', 'bretagne', true),
  ('Quelle ville est surnommée ''la cité des Ducs'' ?', 'Nantes', 'Rennes', 'Vannes', 'Quimper', 'A', 'bretagne', true),
  ('Quel est le point le plus à l''ouest de la Bretagne continentale ?', 'Pointe du Raz', 'Pointe Saint-Mathieu', 'Pointe de Pen-Hir', 'Pointe de Corsen', 'D', 'bretagne', true),
  ('La Bretagne compte combien de départements administratifs ?', '3', '4', '5', '6', 'B', 'bretagne', true),
  ('Quel est le plus grand lac naturel de Bretagne ?', 'Lac de Guerlédan', 'Lac au Duc', 'Lac de Grand-Lieu', 'Aucun, tous artificiels', 'D', 'bretagne', true),
  ('Quelle île est surnommée ''la perle de l''Atlantique'' ?', 'Belle-Île-en-Mer', 'Île de Groix', 'Île d''Ouessant', 'Île de Bréhat', 'A', 'bretagne', true),
  ('Quel phare est le plus haut d''Europe ?', 'Phare de Créac''h', 'Phare de l''Île Vierge', 'Phare d''Eckmühl', 'Phare du Four', 'B', 'bretagne', true),
  ('Quel est l''emblème floral de la Bretagne ?', 'L''ajonc', 'La bruyère', 'Le genêt', 'L''hortensia', 'A', 'bretagne', true),
  ('Quelle ville accueille le festival des Vieilles Charrues ?', 'Lorient', 'Carhaix', 'Quimper', 'Rennes', 'B', 'bretagne', true),
  ('Quel festival celtique a lieu à Lorient chaque été ?', 'Festival du Bout du Monde', 'Festival Interceltique', 'Fest-noz Mondial', 'Festival Yaouank', 'B', 'bretagne', true),
  ('Comment dit-on ''bonjour'' en breton ?', 'Kenavo', 'Demat', 'Mat eo', 'Trugarez', 'B', 'bretagne', true),
  ('Que signifie ''kenavo'' en breton ?', 'Bonjour', 'Merci', 'Au revoir', 'Santé', 'C', 'bretagne', true),
  ('Que signifie ''trugarez'' en breton ?', 'Pardon', 'Merci', 'Bienvenue', 'S''il vous plaît', 'B', 'bretagne', true),
  ('Le drapeau breton s''appelle ?', 'Gwenn ha Du', 'Bro Gozh', 'Triskell', 'Hermine', 'A', 'bretagne', true),
  ('Combien de bandes compte le Gwenn ha Du ?', '7', '9', '11', '13', 'B', 'bretagne', true),
  ('Que représentent les mouchetures d''hermine sur le drapeau breton ?', 'Les ducs', 'Les évêchés', 'Les neuf saints fondateurs', 'Aucune signification', 'A', 'bretagne', true),
  ('Le triskell est composé de combien de branches ?', '2', '3', '4', '5', 'B', 'bretagne', true),
  ('Quelle ville bretonne est célèbre pour ses remparts intacts ?', 'Saint-Malo', 'Concarneau', 'Vannes', 'Dinan', 'A', 'bretagne', true),
  ('Qui était surnommé ''le roi des corsaires'' à Saint-Malo ?', 'Surcouf', 'Duguay-Trouin', 'Jacques Cartier', 'Jean Bart', 'A', 'bretagne', true),
  ('Quel navigateur malouin a découvert le Canada ?', 'Surcouf', 'Jacques Cartier', 'La Pérouse', 'Bougainville', 'B', 'bretagne', true),
  ('Quelle est la plus grande ville de Bretagne en population ?', 'Brest', 'Rennes', 'Nantes (historique)', 'Quimper', 'B', 'bretagne', true),
  ('Le Mont-Saint-Michel est en Bretagne ou en Normandie ?', 'Bretagne', 'Normandie', 'Pays-de-la-Loire', 'Aucun des trois', 'B', 'bretagne', true),
  ('Quelle baie sépare la Bretagne de la Normandie ?', 'Baie de Quiberon', 'Baie de Douarnenez', 'Baie du Mont-Saint-Michel', 'Baie d''Audierne', 'C', 'bretagne', true),
  ('Quel est le plus vieux festival celtique de Bretagne ?', 'Vieilles Charrues', 'Festival de Cornouaille', 'Festival Interceltique', 'Bout du Monde', 'B', 'bretagne', true),
  ('Le Fest-noz est inscrit au patrimoine immatériel de l''UNESCO depuis ?', '2005', '2010', '2012', '2015', 'C', 'bretagne', true),
  ('Que veut dire ''fest-noz'' en breton ?', 'Fête de jour', 'Fête de nuit', 'Grande fête', 'Fête de printemps', 'B', 'bretagne', true),
  ('Quel instrument est typiquement breton ?', 'Cornemuse écossaise', 'Biniou', 'Vielle à roue', 'Accordéon diatonique', 'B', 'bretagne', true),
  ('La bombarde se joue souvent avec ?', 'Le violon', 'Le biniou', 'L''accordéon', 'La harpe', 'B', 'bretagne', true),
  ('Quel est le nom de la harpe celtique ?', 'Telenn', 'Bombarde', 'Veuze', 'Cithare', 'A', 'bretagne', true),
  ('Quel saint est patron de la Bretagne ?', 'Saint Yves', 'Saint Patrick', 'Saint Anne', 'Saint Corentin', 'C', 'bretagne', true),
  ('Combien y a-t-il de saints fondateurs de la Bretagne ?', '5', '7', '9', '12', 'B', 'bretagne', true),
  ('Le Tro Breizh est ?', 'Une course', 'Un pèlerinage', 'Une danse', 'Un plat', 'B', 'bretagne', true),
  ('Quelle ville accueille les Transmusicales ?', 'Brest', 'Rennes', 'Quimper', 'Saint-Malo', 'B', 'bretagne', true),
  ('Quel club de foot évolue à Rennes ?', 'FC Lorient', 'Stade Rennais', 'EA Guingamp', 'FC Nantes', 'B', 'bretagne', true),
  ('Quel maillot porte le Stade Rennais ?', 'Rouge et noir', 'Bleu et blanc', 'Vert et blanc', 'Jaune et noir', 'A', 'bretagne', true),
  ('Quelle ville accueille le club EA Guingamp ?', 'Guingamp', 'Brest', 'Lannion', 'Saint-Brieuc', 'A', 'bretagne', true),
  ('Quel est le surnom des supporters lorientais ?', 'Les Merlus', 'Les Pirates', 'Les Corsaires', 'Les Crabes', 'A', 'bretagne', true),
  ('Quel artiste a chanté ''Dans les prisons de Nantes'' ?', 'Tri Yann', 'Alan Stivell', 'Nolwenn Leroy', 'Yann Tiersen', 'A', 'bretagne', true),
  ('Quel musicien breton est connu pour la harpe celtique ?', 'Yann Tiersen', 'Alan Stivell', 'Denez Prigent', 'Gilles Servat', 'B', 'bretagne', true),
  ('Qui a composé la BO d''Amélie Poulain ?', 'Yann Tiersen', 'Michel Legrand', 'Vladimir Cosma', 'Alexandre Desplat', 'A', 'bretagne', true),
  ('Le Bro Gozh ma Zadoù est ?', 'L''hymne breton', 'Une danse', 'Un fest-noz', 'Une bière', 'A', 'bretagne', true),
  ('Quel est le climat dominant de la Bretagne ?', 'Méditerranéen', 'Océanique tempéré', 'Continental', 'Montagnard', 'B', 'bretagne', true),
  ('Combien de kilomètres de côtes compte la Bretagne ?', '~1 200 km', '~2 700 km', '~4 000 km', '~5 500 km', 'B', 'bretagne', true),
  ('Quelle est la pointe la plus connue du Finistère ?', 'Pointe du Raz', 'Pointe du Grouin', 'Pointe de l''Arcouest', 'Pointe du Van', 'A', 'bretagne', true),
  ('Quelle ville abrite l''Océanopolis ?', 'Concarneau', 'Brest', 'Roscoff', 'Saint-Malo', 'B', 'bretagne', true),
  ('Le Cap Sizun se trouve dans quel département ?', 'Côtes-d''Armor', 'Morbihan', 'Finistère', 'Ille-et-Vilaine', 'C', 'bretagne', true),
  ('Quelle est la plus haute colline de Bretagne ?', 'Roc''h Ruz', 'Mont-Dol', 'Roc''h Trevezel', 'Ménez Hom', 'A', 'bretagne', true),
  ('Le golfe du Morbihan compte combien d''îles selon la légende ?', 'Une par jour de l''année', '100', '52', '365 sauf 6 disparues', 'A', 'bretagne', true),
  ('Quelle ville est célèbre pour ses alignements mégalithiques ?', 'Locronan', 'Carnac', 'Vannes', 'Auray', 'B', 'bretagne', true),
  ('Combien y a-t-il de menhirs alignés à Carnac (environ) ?', '300', '1 000', '3 000', '10 000', 'C', 'bretagne', true),
  ('Quel parc naturel régional traverse la Bretagne intérieure ?', 'Parc d''Armorique', 'Parc des Volcans', 'Parc du Morvan', 'Parc des Landes de Gascogne', 'A', 'bretagne', true),
  ('Quel est le plus grand port de pêche français ?', 'Lorient', 'Boulogne-sur-Mer', 'Concarneau', 'Le Guilvinec', 'B', 'bretagne', true),
  ('Concarneau est célèbre pour ?', 'Sa ville close', 'Son aquarium', 'Sa cathédrale', 'Ses thermes', 'A', 'bretagne', true),
  ('Quelle ville s''appelait jadis ''Aleth'' ?', 'Saint-Malo', 'Dinard', 'Saint-Brieuc', 'Cancale', 'A', 'bretagne', true),
  ('Cancale est célèbre pour ?', 'Ses crêpes', 'Ses huîtres', 'Ses moules', 'Son cidre', 'B', 'bretagne', true),
  ('Roscoff est célèbre pour ?', 'Ses oignons rosés', 'Ses pommes', 'Ses fraises', 'Ses artichauts', 'A', 'bretagne', true),
  ('Plougastel est célèbre pour ?', 'Les fraises', 'Les framboises', 'Les cerises', 'Les pommes', 'A', 'bretagne', true),
  ('Quelle ville produit la fameuse ''cotriade'' ?', 'Lorient', 'Douarnenez', 'Le Guilvinec', 'Aucune ville précise', 'D', 'bretagne', true),
  ('La cotriade est ?', 'Une bière', 'Une soupe de poissons', 'Un fromage', 'Une danse', 'B', 'bretagne', true),
  ('Quel poète breton a écrit ''Le Lis dans la vallée'' ?', 'Chateaubriand', 'Renan', 'Hugo', 'Lamartine', 'A', 'bretagne', true),
  ('Chateaubriand est né dans quelle ville bretonne ?', 'Saint-Malo', 'Combourg', 'Dinan', 'Rennes', 'A', 'bretagne', true),
  ('Quel philosophe breton a écrit ''Vie de Jésus'' ?', 'Renan', 'Sartre', 'Comte', 'Bergson', 'A', 'bretagne', true),
  ('Quelle bande dessinée se passe en Bretagne (Armorique) ?', 'Tintin', 'Astérix', 'Spirou', 'Lucky Luke', 'B', 'bretagne', true),
  ('Quel est le nom du village d''Astérix ?', 'Inconnu', 'Babaorum', 'Aquarium', 'Petitbonum', 'A', 'bretagne', true),
  ('Quelle ville a inspiré le créateur d''Astérix ?', 'Erquy', 'Carnac', 'Locronan', 'Pont-Aven', 'A', 'bretagne', true),
  ('Pont-Aven est célèbre pour ?', 'Ses peintres (école)', 'Ses corsaires', 'Ses thermes', 'Ses oignons', 'A', 'bretagne', true),
  ('Quel peintre a séjourné longuement à Pont-Aven ?', 'Monet', 'Gauguin', 'Cézanne', 'Renoir', 'B', 'bretagne', true),
  ('Quelle ville a un festival de bandes dessinées chaque été ?', 'Quai des Bulles à Saint-Malo', 'Lorient', 'Brest', 'Vannes', 'A', 'bretagne', true),
  ('Quel est le surnom de Brest ?', 'La cité du Ponant', 'La cité corsaire', 'La cité bleue', 'La cité des sept saints', 'A', 'bretagne', true),
  ('Quelle base navale est à Brest ?', 'Marine nationale', 'Aviation civile', 'Légion étrangère', 'Aucune', 'A', 'bretagne', true),
  ('La fête maritime internationale a lieu où ?', 'Saint-Malo', 'Brest', 'Douarnenez', 'Lorient', 'B', 'bretagne', true),
  ('Quel pont relie Brest à la Presqu''île de Plougastel ?', 'Pont Albert-Louppe', 'Pont de l''Iroise', 'Pont de Térénez', 'Tous historiquement', 'D', 'bretagne', true),
  ('Quel film de Jacques Demy se passe à Rochefort puis Cherbourg ?', 'Les Demoiselles de Rochefort', 'Peau d''âne', 'Lola', 'Une chambre en ville', 'A', 'bretagne', true),
  ('Quelle ville bretonne abrite le festival du film britannique ?', 'Brest', 'Dinard', 'Saint-Malo', 'Quimper', 'B', 'bretagne', true),
  ('Le festival de la BD de Quai des Bulles a lieu à ?', 'Brest', 'Quimper', 'Saint-Malo', 'Rennes', 'C', 'bretagne', true),
  ('Combien d''évêchés historiques compte la Bretagne ?', '5', '7', '9', '11', 'C', 'bretagne', true),
  ('Quelle duchesse a épousé deux rois de France ?', 'Anne de Bretagne', 'Aliénor d''Aquitaine', 'Catherine de Médicis', 'Marguerite de Valois', 'A', 'bretagne', true),
  ('Anne de Bretagne a épousé Charles VIII puis ?', 'Henri II', 'Louis XII', 'François Ier', 'Henri III', 'B', 'bretagne', true),
  ('En quelle année la Bretagne fut-elle rattachée à la France ?', '1488', '1532', '1547', '1589', 'B', 'bretagne', true),
  ('Quel château abrite le tombeau d''Anne de Bretagne ?', 'Château de Nantes', 'Saint-Denis', 'Versailles', 'Fontainebleau', 'B', 'bretagne', true),
  ('Quel est le nom du château ducal à Nantes ?', 'Château des ducs de Bretagne', 'Château d''If', 'Château de Brest', 'Château de Suscinio', 'A', 'bretagne', true),
  ('Suscinio est un château situé ?', 'Dans le Finistère', 'En presqu''île de Rhuys', 'À Saint-Malo', 'À Vannes', 'B', 'bretagne', true),
  ('Quelle station balnéaire fut surnommée ''la Reine de la Côte d''Émeraude'' ?', 'Saint-Malo', 'Cancale', 'Dinard', 'Saint-Lunaire', 'C', 'bretagne', true),
  ('La Côte de Granit Rose se trouve dans ?', 'Morbihan', 'Finistère', 'Côtes-d''Armor', 'Ille-et-Vilaine', 'C', 'bretagne', true),
  ('Quel village est célèbre sur la Côte de Granit Rose ?', 'Ploumanac''h', 'Erquy', 'Cancale', 'Saint-Lunaire', 'A', 'bretagne', true),
  ('Quelle ville est appelée ''la Venise de l''Ouest'' ?', 'Vannes', 'Rennes', 'Brest', 'Quimper', 'B', 'bretagne', true),
  ('Le Parlement de Bretagne se trouve à ?', 'Nantes', 'Rennes', 'Vannes', 'Quimper', 'B', 'bretagne', true),
  ('En quelle année eut lieu l''incendie du Parlement de Bretagne ?', '1972', '1994', '1999', '2002', 'B', 'bretagne', true),
  ('Quel est le nom du métro de Rennes ?', 'VAL', 'Métrobus', 'STAR', 'TAG', 'C', 'bretagne', true),
  ('Quelle ligne de TGV dessert Rennes depuis Paris en moins de 1h30 ?', 'LGV Atlantique', 'LGV Bretagne-Pays de la Loire', 'LGV Sud-Ouest', 'LGV Nord', 'B', 'bretagne', true),
  ('Quelle race de cheval est originaire de Bretagne ?', 'Le Trait Breton', 'Le Comtois', 'L''Ardennais', 'Le Percheron', 'A', 'bretagne', true),
  ('Quelle race bovine est typiquement bretonne ?', 'Pie Noir', 'Charolaise', 'Limousine', 'Salers', 'A', 'bretagne', true),
  ('Quel chien est originaire de Bretagne ?', 'L''épagneul breton', 'Le briard', 'Le berger picard', 'Le bouvier des Flandres', 'A', 'bretagne', true),
  ('Quelle est la couleur des hermines du blason breton ?', 'Bleues', 'Rouges', 'Noires', 'Vertes', 'C', 'bretagne', true),
  ('Combien d''hermines compte le drapeau breton ?', '11', '9', '7', 'Indéfini', 'A', 'bretagne', true),
  ('Quel poète a écrit ''Le Cheval d''orgueil'' ?', 'Pierre-Jakez Hélias', 'Glenmor', 'Anjela Duval', 'Xavier Grall', 'A', 'bretagne', true),
  ('Quelle ville accueille le Festival du Bout du Monde ?', 'Crozon', 'Brest', 'Concarneau', 'Lorient', 'A', 'bretagne', true),
  ('Quel est le pont le plus long de Bretagne ?', 'Pont de Saint-Nazaire', 'Pont de Térénez', 'Pont de l''Iroise', 'Viaduc de Morlaix', 'A', 'bretagne', true),
  ('Quel viaduc célèbre traverse Morlaix ?', 'Viaduc de Morlaix', 'Viaduc de Garabit', 'Viaduc de Millau', 'Viaduc de la Souleuvre', 'A', 'bretagne', true),
  ('Combien d''arches compte le viaduc de Morlaix ?', '9', '12', '14', '17', 'C', 'bretagne', true),
  ('Quelle ville bretonne est jumelée avec Cardiff ?', 'Nantes', 'Rennes', 'Brest', 'Lorient', 'B', 'bretagne', true),
  ('Quelle ville accueille le Mondial le Mans ?', 'Nantes', 'Rennes', 'Le Mans', 'Angers', 'C', 'bretagne', true),
  ('Quel département breton borde la Manche au nord ?', 'Finistère', 'Côtes-d''Armor', 'Morbihan', 'Ille-et-Vilaine', 'B', 'bretagne', true),
  ('Quel département borde l''Atlantique au sud ?', 'Finistère', 'Côtes-d''Armor', 'Morbihan', 'Ille-et-Vilaine', 'C', 'bretagne', true),
  ('Quelle est la mer entre Bretagne et Royaume-Uni ?', 'Mer du Nord', 'Manche', 'Mer Celtique', 'Mer d''Iroise', 'B', 'bretagne', true),
  ('Quelle mer baigne Brest ?', 'Mer d''Iroise', 'Manche', 'Atlantique', 'Mer Celtique', 'A', 'bretagne', true),
  ('Quel courant marin influence le climat breton ?', 'Gulf Stream', 'Humboldt', 'Labrador', 'Benguela', 'A', 'bretagne', true),
  ('Quelle est la langue régionale parlée en Haute-Bretagne ?', 'Breton', 'Gallo', 'Normand', 'Picard', 'B', 'bretagne', true),
  ('Le breton est une langue ?', 'Romane', 'Germanique', 'Celtique', 'Slave', 'C', 'bretagne', true),
  ('Quelle famille linguistique inclut le breton ?', 'Brittonique', 'Goidélique', 'Italique', 'Iranienne', 'A', 'bretagne', true),
  ('Le breton est cousin de ?', 'Gallois et cornique', 'Irlandais et écossais', 'Basque', 'Catalan', 'A', 'bretagne', true),
  ('Combien de locuteurs parlent breton aujourd''hui (estimation) ?', '10 000', '100 000', '200 000', '1 million', 'C', 'bretagne', true),
  ('Diwan est un réseau ?', 'D''écoles bilingues breton', 'De boulangeries', 'De crêperies', 'De pharmacies', 'A', 'bretagne', true),
  ('Quel est le nom du fameux gâteau breton aux pruneaux ?', 'Far breton', 'Kouign-amann', 'Quatre-quarts', 'Galette bretonne', 'A', 'bretagne', true),
  ('Le kouign-amann est originaire de ?', 'Quimper', 'Douarnenez', 'Brest', 'Vannes', 'B', 'bretagne', true),
  ('Que signifie ''kouign-amann'' en breton ?', 'Gâteau au sucre', 'Gâteau au beurre', 'Gâteau au sel', 'Gâteau au lait', 'B', 'bretagne', true),
  ('Le quatre-quarts breton est composé de ?', '4 ingrédients à parts égales', '4 étages', '4 saveurs', '4 cuissons', 'A', 'bretagne', true),
  ('Le palet breton est un biscuit à base de ?', 'Beurre salé', 'Miel', 'Lait', 'Caramel', 'A', 'bretagne', true),
  ('Le caramel au beurre salé est originaire de ?', 'Quiberon', 'Saint-Malo', 'Concarneau', 'Vannes', 'A', 'bretagne', true),
  ('Qui a inventé le caramel au beurre salé ?', 'Henri Le Roux', 'Pierre Hermé', 'Bernard Loiseau', 'Joël Robuchon', 'A', 'bretagne', true),
  ('Quelle est la capitale du caramel au beurre salé ?', 'Quiberon', 'Cancale', 'Roscoff', 'Concarneau', 'A', 'bretagne', true),
  ('Le sel de Guérande est ?', 'Un sel de mine', 'Un sel marin', 'Un sel artificiel', 'Un sel de roche', 'B', 'bretagne', true),
  ('Quel est le nom du paludier ?', 'Celui qui pêche', 'Celui qui récolte le sel', 'Celui qui élève des huîtres', 'Celui qui plante', 'B', 'bretagne', true),
  ('La fleur de sel se récolte ?', 'À l''aube', 'Quand il pleut', 'L''été par temps sec', 'L''hiver', 'C', 'bretagne', true),
  ('Quelle est la couleur du sel de Guérande brut ?', 'Blanc pur', 'Gris', 'Rose', 'Beige', 'B', 'bretagne', true),
  ('Quelle est la spécialité de la ville de Pont-Aven ?', 'Galettes pur beurre', 'Caramels', 'Kouign-amann', 'Far', 'A', 'bretagne', true),
  ('Traou Mad signifie en breton ?', 'Bonnes choses', 'Petites galettes', 'Pâtes croquantes', 'Beurre frais', 'A', 'bretagne', true),
  ('Quelle bière bretonne est brassée à Morlaix ?', 'Coreff', 'Britt', 'Telenn Du', 'Sant Erwann', 'A', 'bretagne', true),
  ('Quelle bière au sarrasin existe en Bretagne ?', 'Telenn Du', 'Coreff blonde', 'Britt blonde', 'Lancelot', 'A', 'bretagne', true),
  ('Quelle brasserie breton produit la ''Lancelot'' ?', 'Brasserie Lancelot', 'Coreff', 'Britt', 'Mor Braz', 'A', 'bretagne', true),
  ('Quel est le nom du whisky breton ?', 'Eddu', 'Glann ar Mor', 'Armorik', 'Tous existent', 'D', 'bretagne', true),
  ('Quel chouchen est typique de Bretagne ?', 'Hydromel breton', 'Cidre fort', 'Pommeau', 'Lambig', 'A', 'bretagne', true),
  ('Le chouchen est à base de ?', 'Pomme', 'Miel', 'Sarrasin', 'Orge', 'B', 'bretagne', true),
  ('Le lambig est ?', 'Une eau-de-vie de cidre', 'Un vin', 'Une bière', 'Un fromage', 'A', 'bretagne', true),
  ('Le pommeau breton est un mélange de ?', 'Cidre et lambig', 'Jus de pomme et eau-de-vie', 'Cidre et calvados', 'Cidre et vin', 'B', 'bretagne', true),
  ('Quelle AOP protège le cidre breton ?', 'AOP Cornouaille', 'AOP Pays d''Auge', 'AOP Domfront', 'Aucune AOP existante', 'A', 'bretagne', true),
  ('L''AOP Cornouaille concerne ?', 'Le cidre', 'Les huîtres', 'Les galettes', 'Le beurre', 'A', 'bretagne', true),
  ('Combien de variétés de pommes à cidre en Bretagne (environ) ?', 'Une dizaine', 'Une trentaine', 'Plus de 600 répertoriées', 'Plus de 2000', 'C', 'bretagne', true),
  ('Le beurre breton est traditionnellement ?', 'Doux', 'Demi-sel ou salé', 'Allégé', 'Bio', 'B', 'bretagne', true),
  ('Pourquoi le beurre breton est-il salé historiquement ?', 'Goût', 'Conservation, gabelle évitée', 'Mode', 'Tradition récente', 'B', 'bretagne', true),
  ('La gabelle était ?', 'Un impôt sur le sel', 'Un impôt sur le pain', 'Un impôt sur le vin', 'Un impôt sur la viande', 'A', 'bretagne', true),
  ('La Bretagne historique était-elle exemptée de gabelle ?', 'Oui', 'Non', 'Partiellement', 'Inconnu', 'A', 'bretagne', true),
  ('Quel sport nautique est très pratiqué en Bretagne ?', 'Surf', 'Voile', 'Kitesurf', 'Tous', 'D', 'bretagne', true),
  ('Quelle course transatlantique part de Saint-Malo ?', 'Vendée Globe', 'Route du Rhum', 'Volvo Ocean Race', 'Transat Jacques Vabre', 'B', 'bretagne', true),
  ('La Route du Rhum a lieu tous les ?', '2 ans', '3 ans', '4 ans', '5 ans', 'C', 'bretagne', true),
  ('Quelle ville arrive la Route du Rhum ?', 'Pointe-à-Pitre', 'Fort-de-France', 'Saint-Denis', 'Cayenne', 'A', 'bretagne', true),
  ('Quel est le nom du Vendée Globe en breton ?', 'Course solo non-stop', 'Tour du monde sans escale', 'Aucun nom breton officiel', 'Tro ar bed', 'C', 'bretagne', true),
  ('Quel skipper breton a gagné la Route du Rhum 2018 ?', 'François Gabart', 'Francis Joyon', 'Loïck Peyron', 'Armel Le Cléac''h', 'B', 'bretagne', true),
  ('Quel skipper a remporté le Vendée Globe 2017 ?', 'Armel Le Cléac''h', 'François Gabart', 'Michel Desjoyeaux', 'Jean Le Cam', 'A', 'bretagne', true),
  ('Eric Tabarly était originaire de ?', 'Nantes', 'Lorient', 'Brest', 'Saint-Malo', 'A', 'bretagne', true),
  ('Quel bateau mythique était piloté par Tabarly ?', 'Pen Duick', 'Géronimo', 'Macif', 'Banque Populaire', 'A', 'bretagne', true),
  ('La Cité de la Voile Eric Tabarly est à ?', 'Lorient', 'Brest', 'Saint-Malo', 'Nantes', 'A', 'bretagne', true),
  ('Le golfe du Morbihan est situé près de ?', 'Brest', 'Vannes', 'Lorient', 'Quimper', 'B', 'bretagne', true),
  ('Quelle île est la plus grande du golfe du Morbihan ?', 'Île aux Moines', 'Île d''Arz', 'Île de Batz', 'Île de Sein', 'A', 'bretagne', true),
  ('Quelle île célèbre est près de la Pointe du Raz ?', 'Île de Sein', 'Île d''Ouessant', 'Île de Bréhat', 'Belle-Île', 'A', 'bretagne', true),
  ('Ouessant est connu pour son ?', 'Vent', 'Mouton noir', 'Phare', 'Tous', 'D', 'bretagne', true),
  ('Combien de moutons d''Ouessant existent (race) ?', 'Quelques milliers', 'Plusieurs millions', 'Race éteinte', 'Inconnu', 'A', 'bretagne', true),
  ('Quelle est la plus petite race ovine d''Europe ?', 'Mouton d''Ouessant', 'Mouton de Soay', 'Mérinos', 'Texel', 'A', 'bretagne', true),
  ('Quel chant marin est emblématique de la Bretagne ?', 'Le Pen Duick', 'Le 31 du mois d''août', 'Le Marin de Bretagne', 'Tous existent', 'D', 'bretagne', true),
  ('Quelle danse bretonne se danse en chaîne ?', 'Gavotte', 'An Dro', 'Hanter Dro', 'Toutes', 'D', 'bretagne', true),
  ('La gavotte vient de quel pays ?', 'Léon', 'Cornouaille', 'Trégor', 'Vannetais', 'B', 'bretagne', true),
  ('Combien de pays traditionnels en Bretagne (environ) ?', 'Une dizaine', 'Plus de 60', '5', '20', 'B', 'bretagne', true),
  ('La coiffe bigoudène est haute de ?', '10 cm', '20 cm', '30 cm ou plus', '5 cm', 'C', 'bretagne', true),
  ('La coiffe bigoudène vient de la région de ?', 'Quimper', 'Pont-l''Abbé', 'Concarneau', 'Douarnenez', 'B', 'bretagne', true),
  ('Quel est le pays bigouden ?', 'Sud-ouest du Finistère', 'Nord du Finistère', 'Côtes-d''Armor', 'Morbihan', 'A', 'bretagne', true),
  ('Quel est le légume emblématique de Saint-Pol-de-Léon ?', 'Artichaut', 'Chou-fleur', 'Carotte', 'Pomme de terre', 'B', 'bretagne', true),
  ('Le ''Légumes de France'' a son siège à ?', 'Saint-Pol-de-Léon', 'Paris', 'Roscoff', 'Brest', 'A', 'bretagne', true),
  ('L''oignon de Roscoff est protégé par ?', 'AOP', 'IGP', 'Label Rouge', 'AB', 'A', 'bretagne', true),
  ('Quelle est la couleur de l''oignon de Roscoff ?', 'Blanc', 'Jaune', 'Rosé', 'Rouge', 'C', 'bretagne', true),
  ('Quel petit fruit rouge est cultivé à Plougastel ?', 'Fraise', 'Framboise', 'Cerise', 'Mûre', 'A', 'bretagne', true),
  ('Quel est le surnom du Finistère ?', 'Bout du monde', 'Finis Terrae', 'Pointe', 'Cap', 'B', 'bretagne', true),
  ('''Penn ar Bed'' signifie ?', 'Pointe du monde', 'Bout du monde', 'Tête de la mer', 'Cap au vent', 'B', 'bretagne', true),
  ('Quelle ville bretonne accueille un sous-marin musée ?', 'Saint-Nazaire (Espadon)', 'Brest', 'Lorient', 'Toutes', 'D', 'bretagne', true),
  ('Quel sous-marin nucléaire est basé en Bretagne ?', 'Le Triomphant', 'Le Téméraire', 'Le Vigilant', 'Les SNLE à l''Île Longue', 'D', 'bretagne', true),
  ('L''Île Longue se trouve à ?', 'Brest (Crozon)', 'Lorient', 'Saint-Malo', 'Nantes', 'A', 'bretagne', true),
  ('Quel est le sport régional traditionnel en Bretagne ?', 'Lutte bretonne (gouren)', 'Pelote', 'Sumo', 'Boxe', 'A', 'bretagne', true),
  ('Le gouren est un type de ?', 'Lutte', 'Course', 'Danse', 'Saut', 'A', 'bretagne', true),
  ('Quelle ville accueille la ''Redadeg'' ?', 'Une seule', 'Itinérant', 'Rennes', 'Quimper', 'B', 'bretagne', true),
  ('La Redadeg est une course pour ?', 'Le breton', 'Le climat', 'La paix', 'Le sport', 'A', 'bretagne', true),
  ('La devise de la Bretagne est ?', 'Potius mori quam foedari', 'Liberté Égalité Fraternité', 'Plus est en vous', 'Sub umbra alarum tuarum', 'A', 'bretagne', true),
  ('Que signifie ''Potius mori quam foedari'' ?', 'Plutôt mourir que se déshonorer', 'Plutôt vivre que mourir', 'Plutôt rire que pleurer', 'Plutôt manger que boire', 'A', 'bretagne', true),
  ('Quel est le code département du Morbihan ?', '29', '35', '56', '22', 'C', 'bretagne', true),
  ('Quel est le code des Côtes-d''Armor ?', '22', '29', '35', '56', 'A', 'bretagne', true),
  ('Code du Finistère ?', '22', '29', '35', '56', 'B', 'bretagne', true),
  ('Code de l''Ille-et-Vilaine ?', '22', '29', '35', '56', 'C', 'bretagne', true),
  ('Quelle est la capitale historique de la Bretagne ?', 'Rennes', 'Nantes', 'Vannes', 'Quimper', 'B', 'bretagne', true),
  ('Pourquoi Nantes est-elle hors région Bretagne aujourd''hui ?', 'Découpage administratif 1956', 'Décision référendaire', 'Choix royal', 'Hasard', 'A', 'bretagne', true),
  ('Quelle est la fête nationale bretonne ?', '1er mai', '21 juin', 'Pas officielle, souvent 19 mai', '14 juillet', 'C', 'bretagne', true),
  ('Le 19 mai correspond à ?', 'Saint Yves', 'Saint Anne', 'Saint Patrick', 'Saint Corentin', 'A', 'bretagne', true),
  ('Saint Yves est patron des ?', 'Avocats', 'Marins', 'Boulangers', 'Paysans', 'A', 'bretagne', true),
  ('Quelle ville est célèbre pour son pardon de Saint Yves ?', 'Tréguier', 'Quimper', 'Vannes', 'Locronan', 'A', 'bretagne', true),
  ('Le pardon est ?', 'Une fête religieuse bretonne', 'Une danse', 'Un plat', 'Un instrument', 'A', 'bretagne', true),
  ('Quelle est la basilique de Sainte-Anne d''Auray ?', 'Lieu de pèlerinage', 'Cathédrale', 'Abbaye', 'Couvent', 'A', 'bretagne', true),
  ('Quel est l''animal légendaire de la forêt de Brocéliande ?', 'Cerf blanc', 'Loup-garou', 'Korrigan', 'Tous', 'D', 'bretagne', true),
  ('Brocéliande est aujourd''hui appelée ?', 'Forêt de Paimpont', 'Forêt de Fougères', 'Forêt du Gâvre', 'Forêt de Quénécan', 'A', 'bretagne', true),
  ('Selon la légende, qui dort sous Brocéliande ?', 'Merlin', 'Arthur', 'Lancelot', 'Viviane', 'A', 'bretagne', true),
  ('La fontaine de Barenton serait celle de ?', 'Merlin', 'Viviane', 'Morgane', 'Brocéliande', 'A', 'bretagne', true),
  ('Quelle ville bretonne possède un menhir indicateur ?', 'Locmariaquer', 'Carnac', 'Plouharnel', 'Toutes', 'D', 'bretagne', true),
  ('Le grand menhir brisé pèse environ ?', '100 tonnes', '200 tonnes', '280 tonnes', '500 tonnes', 'C', 'bretagne', true),
  ('Quel est le tumulus le plus connu de Carnac ?', 'Saint-Michel', 'Kercado', 'Mané-Lud', 'Tous célèbres', 'A', 'bretagne', true),
  ('Combien d''années avant J.-C. datent les mégalithes de Carnac ?', '1 000', '3 000', '4 500-3 300', '10 000', 'C', 'bretagne', true),
  ('Quelle farine est utilisée pour la galette ?', 'Froment', 'Sarrasin (blé noir)', 'Maïs', 'Seigle', 'B', 'food', true),
  ('Le sarrasin est aussi appelé ?', 'Blé noir', 'Blé dur', 'Blé tendre', 'Blé d''Inde', 'A', 'food', true),
  ('Le sarrasin est botaniquement ?', 'Une céréale', 'Une polygonacée', 'Une graminée', 'Une légumineuse', 'B', 'food', true),
  ('Quelle est la garniture classique de la galette complète ?', 'Jambon-œuf-fromage', 'Poulet-curry', 'Saumon-épinard', 'Andouille-pomme', 'A', 'food', true),
  ('La crêpe sucrée est faite avec ?', 'Sarrasin', 'Froment', 'Riz', 'Maïs', 'B', 'food', true),
  ('Quel ustensile sert à étaler la pâte ?', 'Rozell', 'Spanell', 'Spatule', 'Tous', 'A', 'food', true),
  ('Comment s''appelle la spatule à crêpes en breton ?', 'Spanell', 'Rozell', 'Krampouez', 'Bilig', 'A', 'food', true),
  ('Comment s''appelle la plaque de cuisson ?', 'Bilig', 'Krampouezh', 'Rozell', 'Plomenn', 'A', 'food', true),
  ('Krampouezh signifie ?', 'Crêpe', 'Galette', 'Beurre', 'Lait', 'A', 'food', true),
  ('Quelle est la garniture ''forestière'' classique ?', 'Champignons-crème', 'Lard-oignon', 'Saumon-aneth', 'Chèvre-miel', 'A', 'food', true),
  ('La galette ''andouille'' contient ?', 'Andouille de Guémené', 'Saucisson', 'Andouillette', 'Boudin', 'A', 'food', true),
  ('L''andouille de Guémené est faite de ?', 'Robes de porc enroulées', 'Mélange haché', 'Boyaux mélangés', 'Foie', 'A', 'food', true),
  ('Quel cidre accompagne la galette ?', 'Cidre brut breton', 'Vin rouge', 'Bière blonde', 'Eau gazeuse', 'A', 'food', true),
  ('Comment se boit traditionnellement le cidre ?', 'Dans une bolée', 'Dans un verre à pied', 'Dans un mug', 'Dans un calice', 'A', 'food', true),
  ('Une bolée est ?', 'Un bol/tasse en faïence', 'Un grand verre', 'Une carafe', 'Un broc', 'A', 'food', true),
  ('Quelle marque de faïence est célèbre à Quimper ?', 'HB Henriot', 'Gien', 'Limoges', 'Sarreguemines', 'A', 'food', true),
  ('Le ''far breton'' classique est garni de ?', 'Pruneaux', 'Raisins secs', 'Pommes', 'Cerises', 'A', 'food', true),
  ('Le far peut aussi se faire aux ?', 'Raisins (far blanc)', 'Cerises', 'Aux deux', 'Avec n''importe quel fruit', 'C', 'food', true),
  ('Le far est un dessert proche du ?', 'Flan', 'Pudding', 'Clafoutis', 'Tous', 'D', 'food', true),
  ('Quel est le secret d''une bonne galette ?', 'Repos de la pâte', 'Plaque très chaude', 'Bonne farine', 'Tous', 'D', 'food', true),
  ('Combien de temps faire reposer la pâte de sarrasin ?', '10 min', '1 heure', 'Plusieurs heures à une nuit', '1 semaine', 'C', 'food', true),
  ('Le sarrasin contient-il du gluten ?', 'Oui beaucoup', 'Non', 'Un peu', 'Selon la marque', 'B', 'food', true),
  ('La galette est-elle naturellement sans gluten ?', 'Oui si 100% sarrasin', 'Non jamais', 'Seulement si bio', 'Inconnu', 'A', 'food', true),
  ('La crêpe Suzette est flambée à ?', 'Cointreau / Grand Marnier', 'Rhum', 'Calvados', 'Whisky', 'A', 'food', true),
  ('Qui aurait inventé la crêpe Suzette ?', 'Henri Charpentier', 'Auguste Escoffier', 'Paul Bocuse', 'Inconnu', 'A', 'food', true),
  ('Le ''beurre blanc'' est une sauce typique de ?', 'Bretagne / Pays nantais', 'Normandie', 'Provence', 'Alsace', 'A', 'food', true),
  ('Le beurre blanc accompagne souvent ?', 'Brochet ou poisson', 'Bœuf', 'Veau', 'Agneau', 'A', 'food', true),
  ('Le kig ha farz est un plat de ?', 'Léon (Finistère)', 'Cornouaille', 'Vannetais', 'Trégor', 'A', 'food', true),
  ('Kig ha farz se traduit par ?', 'Viande et pâte', 'Viande et farine', 'Bouillon et farce', 'Pot-au-feu breton', 'A', 'food', true),
  ('Quelle viande dans le kig ha farz ?', 'Bœuf et porc', 'Mouton uniquement', 'Poulet', 'Lapin', 'A', 'food', true),
  ('La cotriade est l''équivalent breton de ?', 'Bouillabaisse', 'Pot-au-feu', 'Choucroute', 'Cassoulet', 'A', 'food', true),
  ('Quel poisson dans la cotriade traditionnelle ?', 'Poissons de pêche du jour', 'Saumon uniquement', 'Cabillaud uniquement', 'Sardines uniquement', 'A', 'food', true),
  ('La galette-saucisse est typique de ?', 'Rennes', 'Brest', 'Quimper', 'Vannes', 'A', 'food', true),
  ('Comment se mange la galette-saucisse à Rennes ?', 'Avec moutarde, à la main', 'Avec couteau et fourchette', 'Trempée dans cidre', 'Avec ketchup', 'A', 'food', true),
  ('Le rugby ou le foot rennais ?', 'Foot historiquement lié à galette-saucisse', 'Rugby', 'Les deux', 'Aucun', 'A', 'food', true),
  ('La ''crêpe dentelle'' est originaire de ?', 'Quimper', 'Vannes', 'Brest', 'Saint-Malo', 'A', 'food', true),
  ('Qui a créé la crêpe dentelle (Gavottes) ?', 'Marie-Catherine Cornic', 'Louis Le Roux', 'Henri Le Roux', 'Anonyme', 'A', 'food', true),
  ('En quelle année la crêpe dentelle est-elle née ?', '1820', '1886', '1920', '1955', 'B', 'food', true),
  ('Le ''craquelin'' breton est ?', 'Une brioche craquante', 'Un biscuit sec', 'Une crêpe sèche', 'Une galette dure', 'A', 'food', true),
  ('Le craquelin est typique de ?', 'Saint-Malo', 'Brest', 'Quimper', 'Lorient', 'A', 'food', true),
  ('Le ''morgat'' est ?', 'Une seiche', 'Une plage', 'Les deux', 'Un fromage', 'C', 'food', true),
  ('La ''kig sall'' est ?', 'Viande salée (lard)', 'Soupe', 'Plat de mer', 'Pâté', 'A', 'food', true),
  ('La ''youdig'' / ''yod'' désigne ?', 'Bouillie', 'Soupe de poisson', 'Pâté', 'Saucisse', 'A', 'food', true),
  ('Quelle céréale ancienne pousse bien en Bretagne ?', 'Sarrasin', 'Avoine', 'Seigle', 'Toutes', 'D', 'food', true),
  ('Le ''pâté Hénaff'' est originaire de ?', 'Pouldreuzic (Finistère)', 'Quimper', 'Brest', 'Vannes', 'A', 'food', true),
  ('Quelle est la couleur de la boîte Hénaff ?', 'Bleu et jaune', 'Rouge et blanc', 'Vert', 'Noir', 'A', 'food', true),
  ('Hénaff est fondé en ?', '1907', '1925', '1947', '1960', 'A', 'food', true),
  ('Le ''biscuit LU'' est né à ?', 'Nantes', 'Rennes', 'Brest', 'Quimper', 'A', 'food', true),
  ('LU signifie ?', 'Lefèvre-Utile', 'La Universelle', 'Le Unique', 'Lait Ultra', 'A', 'food', true),
  ('Le ''Petit Beurre LU'' a combien de bords festonnés ?', '52 (semaines)', '12 (mois)', '365', '24', 'A', 'food', true),
  ('Le ''Petit Beurre'' a combien de dents ?', '48', '52', '24', '60', 'A', 'food', true),
  ('Quel poisson est emblématique de Concarneau ?', 'Thon', 'Sardine', 'Maquereau', 'Cabillaud', 'A', 'food', true),
  ('Quel poisson est emblématique de Douarnenez ?', 'Sardine', 'Thon', 'Hareng', 'Saumon', 'A', 'food', true),
  ('La conserve de sardines est née à ?', 'Nantes / Bretagne', 'Marseille', 'Boulogne', 'Bordeaux', 'A', 'food', true),
  ('Quelle est la marque iconique de sardines bretonne ?', 'Connétable', 'La Belle-Iloise', 'Les deux', 'Petit Navire', 'C', 'food', true),
  ('La Belle-Iloise est basée à ?', 'Quiberon', 'Belle-Île', 'Lorient', 'Concarneau', 'A', 'food', true),
  ('L''huître plate est typique de ?', 'Cancale', 'Belon', 'Les deux', 'Marennes', 'C', 'food', true),
  ('L''huître Belon vient de ?', 'Riec-sur-Belon', 'Cancale', 'Marennes', 'Arcachon', 'A', 'food', true),
  ('Quel est le goût caractéristique de l''huître Belon ?', 'Goût de noisette', 'Goût iodé fort', 'Goût sucré', 'Goût neutre', 'A', 'food', true),
  ('Quel coquillage est élevé en baie du Mont-Saint-Michel ?', 'Moule de bouchot', 'Praire', 'Coque', 'Palourde', 'A', 'food', true),
  ('La moule de bouchot bénéficie de ?', 'AOP', 'AOC', 'IGP', 'STG', 'A', 'food', true),
  ('Quelle est la saison des moules de bouchot ?', 'Janvier-mars', 'Juillet-février', 'Toute l''année', 'Mai-août', 'B', 'food', true),
  ('Quel poisson plat est emblématique en Bretagne nord ?', 'Sole', 'Turbot', 'Barbue', 'Tous pêchés', 'D', 'food', true),
  ('Quel crustacé est emblématique de la pêche bretonne ?', 'Langoustine', 'Tourteau', 'Araignée', 'Tous', 'D', 'food', true),
  ('Le tourteau breton est aussi appelé ?', 'Dormeur', 'Crabe vert', 'Crabe royal', 'Étrille', 'A', 'food', true),
  ('Quel est le surnom du homard breton ?', 'Cardinal des mers', 'Roi des mers', 'Bleu de Bretagne', 'Tous donnés', 'A', 'food', true),
  ('Le homard bleu se distingue par ?', 'Sa carapace bleutée vivant', 'Son goût sucré', 'Sa taille', 'Tous', 'A', 'food', true),
  ('La ''soupe de poisson'' bretonne s''appelle ?', 'Cotriade', 'Bouillabaisse', 'Marmite', 'Soupe blanche', 'A', 'food', true),
  ('Le ''pâté de campagne breton'' est protégé par ?', 'IGP', 'AOP', 'Label Rouge', 'Aucun', 'A', 'food', true),
  ('Le ''gâteau breton'' contient surtout ?', 'Beurre, sucre, jaunes d''œuf', 'Lait, farine, eau', 'Sucre, miel, lait', 'Farine, levure, eau', 'A', 'food', true),
  ('Le ''kig ha farz'' se cuit dans ?', 'Une marmite avec sac de toile', 'Un four', 'Une cocotte-minute', 'Une poêle', 'A', 'food', true),
  ('Le ''farz buen'' est ?', 'Une bouillie de blé noir', 'Une crêpe', 'Un pain', 'Une brioche', 'A', 'food', true),
  ('Le ''fars'' du kig ha farz est ?', 'Sucré (raisins) ou nature', 'Toujours salé', 'Toujours sucré', 'Toujours nature', 'A', 'food', true),
  ('Le ''gwastell'' désigne en breton ?', 'Gâteau', 'Crêpe', 'Pain', 'Beurre', 'A', 'food', true),
  ('La ''galette de Pleyben'' est ?', 'Un biscuit pur beurre', 'Une crêpe salée', 'Un pain rond', 'Un pâté', 'A', 'food', true),
  ('Pleyben se trouve dans ?', 'Le Finistère', 'Le Morbihan', 'Les Côtes-d''Armor', 'L''Ille-et-Vilaine', 'A', 'food', true),
  ('Le ''palet d''or'' est typique de ?', 'Moulins (pas Bretagne)', 'Quimper', 'Vannes', 'Brest', 'A', 'food', true),
  ('Le ''kouign patatez'' est ?', 'Galette de pommes de terre', 'Gâteau de pommes', 'Crêpe sucrée', 'Pâté de pommes', 'A', 'food', true),
  ('Le sarrasin a été introduit en Bretagne au ?', 'XIIe siècle', 'XVe siècle', 'XVIIIe siècle', 'XXe siècle', 'B', 'food', true),
  ('Pourquoi le sarrasin a-t-il convenu à la Bretagne ?', 'Sols pauvres et acides', 'Climat chaud', 'Sols riches', 'Climat sec', 'A', 'food', true),
  ('La crêpe à la confiture la plus classique en Bretagne ?', 'Caramel beurre salé', 'Confiture de fraises', 'Nutella', 'Tous courants', 'A', 'food', true),
  ('Quel produit ajouté chaud sur la crêpe transforme tout ?', 'Beurre demi-sel', 'Crème fraîche', 'Lait concentré', 'Sucre glace', 'A', 'food', true),
  ('Une ''galette saucisse'' contient quelle saucisse ?', 'Saucisse grillée de porc', 'Merguez', 'Chipolata', 'Andouille', 'A', 'food', true),
  ('Le ''kig ha farz'' est servi avec ?', 'Un lipig (beurre fondu, oignon)', 'De la moutarde', 'Du ketchup', 'Du miel', 'A', 'food', true),
  ('Le ''lipig'' est ?', 'Sauce au beurre fondu et oignon', 'Une farce', 'Un pain', 'Un dessert', 'A', 'food', true),
  ('Le ''cotignac breton'' existe-t-il ?', 'Non, c''est d''Orléans', 'Oui à Vannes', 'Oui à Brest', 'Oui à Quimper', 'A', 'food', true),
  ('Le ''pain breton'' est souvent ?', 'Au levain naturel', 'Industriel', 'Au lait', 'Brioché', 'A', 'food', true),
  ('Le ''fouée'' est une spécialité de ?', 'Anjou (pas Bretagne)', 'Bretagne', 'Normandie', 'Vendée', 'A', 'food', true),
  ('Le ''gâteau nantais'' est aromatisé au ?', 'Rhum', 'Cognac', 'Calvados', 'Pommeau', 'A', 'food', true),
  ('Le ''curé nantais'' est un ?', 'Fromage', 'Gâteau', 'Vin', 'Pain', 'A', 'food', true),
  ('Le ''curé nantais'' est de quel type ?', 'Pâte molle, croûte lavée', 'Pâte pressée', 'Pâte persillée', 'Frais', 'A', 'food', true),
  ('Le ''muscadet'' est un vin de ?', 'Pays nantais', 'Anjou', 'Touraine', 'Saumur', 'A', 'food', true),
  ('Le muscadet se boit ?', 'Très frais', 'Chambré', 'Tiède', 'Bouillant', 'A', 'food', true),
  ('Quel cépage donne le muscadet ?', 'Melon de Bourgogne', 'Chardonnay', 'Sauvignon', 'Chenin', 'A', 'food', true),
  ('Quelle mention valorise un muscadet ?', 'Sur lie', 'Réserve', 'Vieille vigne', 'Toutes possibles', 'A', 'food', true),
  ('Le ''gros plant du Pays nantais'' est un ?', 'Vin blanc IGP', 'Cidre', 'Bière', 'Eau-de-vie', 'A', 'food', true),
  ('La ''fouace'' bretonne est ?', 'Une brioche', 'Un pain', 'Un biscuit', 'Un gâteau', 'A', 'food', true),
  ('Le ''beurre Bordier'' est de ?', 'Saint-Malo', 'Quimper', 'Brest', 'Vannes', 'A', 'food', true),
  ('Le ''beurre Bordier'' est célèbre pour ?', 'Son barattage manuel', 'Son industrialisation', 'Son packaging', 'Sa publicité', 'A', 'food', true),
  ('Le ''beurre demi-sel'' contient combien de sel ?', '0,5 à 3 %', '5 %', '10 %', '0 %', 'A', 'food', true),
  ('Le ''beurre salé'' contient ?', 'Plus de 3 % de sel', '0 %', '10 %', 'Variable', 'A', 'food', true),
  ('Le ''caramel mou'' typique breton est aussi à base de ?', 'Beurre salé et crème', 'Lait seulement', 'Sucre seulement', 'Miel', 'A', 'food', true),
  ('Quelle confiserie bretonne est emblématique à Pâques ?', 'Œufs de Niniche (Saint-Malo)', 'Niniches de Quiberon', 'Bonbons Glaz', 'Plaisirs sucrés', 'B', 'food', true),
  ('La ''niniche de Quiberon'' est ?', 'Une sucette caramel ou parfumée', 'Un bonbon dur', 'Un chocolat', 'Une praline', 'A', 'food', true),
  ('Combien de parfums de niniches existent (env.) ?', '10', '20', 'Plus de 40', '100', 'C', 'food', true),
  ('La ''galette'' au sens biscuit (pur beurre) contient ?', 'Farine, beurre, sucre, œufs', 'Farine, eau, sel', 'Sarrasin, eau, sel', 'Farine, lait, levure', 'A', 'food', true),
  ('Le label ''Produit en Bretagne'' a quelle couleur dominante ?', 'Bleu', 'Vert', 'Jaune', 'Rouge', 'A', 'food', true),
  ('Combien d''entreprises adhèrent à ''Produit en Bretagne'' ?', 'Une dizaine', 'Une centaine', 'Plus de 400', 'Plus de 5000', 'C', 'food', true),
  ('Quel est le secret d''un bon caramel beurre salé ?', 'Cuisson maîtrisée', 'Beurre demi-sel de qualité', 'Bonne crème', 'Tous', 'D', 'food', true),
  ('Quelle est la température idéale pour un caramel ?', '100°C', '120°C', '150-170°C', '200°C', 'C', 'food', true),
  ('Comment éviter que la crêpe colle ?', 'Bilig bien graissée et chaude', 'Beaucoup d''huile', 'Pâte très épaisse', 'Pâte très froide', 'A', 'food', true),
  ('Quelle huile traditionnelle pour graisser le bilig ?', 'Saindoux ou beurre', 'Huile d''olive', 'Huile de tournesol', 'Margarine', 'A', 'food', true),
  ('Une ''krampouezhérie'' est ?', 'Une crêperie en breton', 'Une boulangerie', 'Une laiterie', 'Un magasin', 'A', 'food', true),
  ('La crêpe se replie classiquement en ?', 'Quatre', 'Trois', 'Deux', 'Roulée', 'A', 'food', true),
  ('Une galette ''complète'' a combien d''ingrédients principaux ?', '3 (jambon, œuf, fromage)', '2', '4', '5', 'A', 'food', true),
  ('Quel fromage classique sur une galette complète ?', 'Emmental râpé', 'Camembert', 'Roquefort', 'Brie', 'A', 'food', true),
  ('Une galette ''chèvre-miel'' contient ?', 'Chèvre, miel, parfois noix', 'Chèvre, sucre', 'Chèvre, sirop d''érable', 'Chèvre, confiture', 'A', 'food', true),
  ('Une galette ''saumon'' classique a ?', 'Saumon fumé, crème, aneth', 'Saumon cru, citron', 'Saumon cuit, ail', 'Saumon, fromage rouge', 'A', 'food', true),
  ('Quel légume oublié est emblématique en Bretagne ?', 'Topinambour', 'Rutabaga', 'Panais', 'Tous cultivés', 'D', 'food', true),
  ('La ''pomme de terre primeur'' bretonne vient de ?', 'Île de Batz', 'Roscoff', 'Tous', 'Cancale', 'C', 'food', true),
  ('La pomme de terre primeur de Noirmoutier est-elle bretonne ?', 'Non, vendéenne', 'Oui', 'Côtes-d''Armor', 'Inconnu', 'A', 'food', true),
  ('Quel fruit rouge breton est célèbre l''été ?', 'Fraise de Plougastel', 'Cerise', 'Framboise', 'Mûre', 'A', 'food', true),
  ('Quelle fête célèbre la fraise à Plougastel ?', 'Fête des Fraises', 'Fête des Pommes', 'Fête du Sarrasin', 'Fête de la Mer', 'A', 'food', true),
  ('Quelle est la spécialité de Pleyben en biscuit ?', 'Galettes pur beurre Pleyben', 'Madeleines', 'Sablés au cumin', 'Brioches', 'A', 'food', true),
  ('Quelle marque historique de biscuit à Pont-Aven ?', 'Traou Mad', 'Le Glazik', 'Loc Maria', 'Kambly', 'A', 'food', true),
  ('Le ''crêpier breton'' utilise quel outil pour étaler ?', 'Le rozell (râteau de bois)', 'Une louche', 'Une raclette', 'Une cuillère', 'A', 'food', true),
  ('Quelle est la circonférence d''une grande galette ?', '20 cm', '30 cm', '40 cm ou plus', '10 cm', 'C', 'food', true),
  ('Le ''gwastell laezh'' est un ?', 'Gâteau au lait', 'Gâteau au beurre', 'Pain au lait', 'Yaourt', 'A', 'food', true),
  ('L''algue ''kombu royal'' se récolte en ?', 'Bretagne nord', 'Méditerranée', 'Atlantique sud', 'Rhône-Alpes', 'A', 'food', true),
  ('Quelle algue se mange en tartare en Bretagne ?', 'Dulse', 'Laitue de mer', 'Wakamé local', 'Toutes possibles', 'D', 'food', true),
  ('Quel ingrédient marin est tendance en cuisine bretonne ?', 'Algues alimentaires', 'Plancton', 'Eau de mer', 'Tous', 'D', 'food', true),
  ('Quelle huile parfumée est typique en Bretagne ?', 'Huile de sarrasin grillé', 'Huile de noisette', 'Huile d''olive', 'Huile de pépin de raisin', 'A', 'food', true),
  ('Le ''beurre de baratte'' diffère par ?', 'Sa texture aérée', 'Sa couleur rose', 'Sa cuisson', 'Sa dureté', 'A', 'food', true),
  ('Combien de litres de lait pour 1 kg de beurre ?', '5', '10', '20-25', '100', 'C', 'food', true),
  ('Le ''lait ribot'' est ?', 'Du babeurre fermenté', 'Du lait cru', 'Du lait UHT', 'Du lait écrémé', 'A', 'food', true),
  ('Avec quoi déguste-t-on traditionnellement le lait ribot ?', 'Avec galettes ou pommes de terre', 'Avec gâteau au chocolat', 'Avec viande', 'Avec poisson', 'A', 'food', true),
  ('Le ''gros sel de Guérande'' est ?', 'Naturel non raffiné', 'Industriel', 'Iodé', 'Fin', 'A', 'food', true),
  ('La fleur de sel se forme ?', 'À la surface des œillets', 'Au fond des marais', 'Sur les rochers', 'Dans le sable', 'A', 'food', true),
  ('Combien de kilos de fleur de sel par récolte (par paludier) ?', 'Très peu (quelques kg/jour)', 'Tonnes/jour', '100 kg/jour', '1 t/an', 'A', 'food', true),
  ('Quelle algue est utilisée pour épaissir (carraghénane) ?', 'Mousse d''Irlande', 'Wakamé', 'Nori', 'Spiruline', 'A', 'food', true),
  ('Le ''goémonier'' est ?', 'Récolteur d''algues', 'Pêcheur', 'Marin-paysan', 'Tous', 'D', 'food', true),
  ('Le ''goémon'' désigne ?', 'Les algues échouées ou récoltées', 'Le sable', 'Le sel', 'Le poisson', 'A', 'food', true),
  ('Quel poisson maigre est emblématique de la Manche bretonne ?', 'Bar de ligne', 'Saumon', 'Truite', 'Carpe', 'A', 'food', true),
  ('Le ''bar de ligne'' est pêché ?', 'À la canne, individuellement', 'Au chalut', 'Au filet', 'Au casier', 'A', 'food', true),
  ('Quelle ville bretonne est célèbre pour le bar de ligne ?', 'Le Guilvinec', 'Saint-Guénolé', 'Tous ports finistériens', 'Saint-Malo', 'C', 'food', true),
  ('Le ''lieu jaune'' est un poisson de ?', 'Côtes bretonnes', 'Méditerranée', 'Atlantique sud', 'Mer Rouge', 'A', 'food', true),
  ('Quelle est la meilleure cuisson pour un homard breton ?', 'Court-bouillon', 'Vapeur', 'Plancha', 'Toutes possibles', 'D', 'food', true),
  ('L''araignée de mer se déguste ?', 'Froide avec mayonnaise', 'Chaude au four', 'Frite', 'Toutes possibles', 'A', 'food', true),
  ('Quelle est la saison des coquilles Saint-Jacques en Bretagne ?', 'Octobre-mai', 'Juin-août', 'Toute l''année', 'Mars-juin', 'A', 'food', true),
  ('La coquille Saint-Jacques de la baie de Saint-Brieuc est ?', 'Pectinée maxima', 'Pectinée jacobaeus', 'Mélange', 'Aucun nom officiel', 'A', 'food', true),
  ('Quel record bat la baie de Saint-Brieuc ?', 'Plus grand gisement de coquilles France', 'Plus profonde', 'Plus salée', 'Plus chaude', 'A', 'food', true),
  ('Quel produit phare de la mer en hiver en Bretagne ?', 'Coquille Saint-Jacques', 'Sardine', 'Thon', 'Anchois', 'A', 'food', true),
  ('Le ''tartare d''algues'' typique se compose de ?', 'Algues hachées, échalote, citron', 'Algues seules', 'Algues sucrées', 'Algues frites', 'A', 'food', true),
  ('Quel ingrédient est l''âme d''une crêpe sucrée ?', 'Beurre demi-sel', 'Vanille', 'Rhum', 'Citron', 'A', 'food', true),
  ('Quelle pâte à crêpe est la plus classique ?', 'Farine, lait, œufs, sucre, beurre', 'Farine et eau', 'Sarrasin et eau', 'Farine et lait sucré', 'A', 'food', true),
  ('La pâte à crêpe doit-elle reposer ?', 'Oui idéalement 1-2h', 'Non', 'Pendant 1 semaine', 'Pendant 5 minutes', 'A', 'food', true),
  ('Pourquoi la pâte doit-elle reposer ?', 'Hydratation farine, gluten détendu', 'Pour la couleur', 'Pour la mousse', 'Pour le goût uniquement', 'A', 'food', true),
  ('Quel parfum est typiquement breton dans les crêpes ?', 'Eau de fleur d''oranger ou rhum', 'Cannelle', 'Cardamome', 'Anis', 'A', 'food', true),
  ('Le ''sucre roux'' utilisé est souvent ?', 'Vergeoise ou sucre brun', 'Sucre glace', 'Sucre cristal', 'Sucre de canne', 'A', 'food', true),
  ('Quelle confiture régionale accompagne les crêpes ?', 'Confiture de lait, caramel', 'Confiture de cynorhodon', 'Confiture de coings', 'Toutes possibles', 'A', 'food', true),
  ('Quel rhum est typiquement utilisé pour flamber ?', 'Rhum agricole', 'Rhum brun', 'Rhum blanc', 'Tous possibles', 'D', 'food', true),
  ('La crêpe se cuit-elle des deux côtés ?', 'Oui, brièvement de chaque côté', 'Non', 'Une seule face', '5 minutes par face', 'A', 'food', true),
  ('Combien de temps cuire une crêpe (env.) ?', '1-2 minutes total', '10 minutes', '30 secondes', '5 minutes', 'A', 'food', true),
  ('Quelle température pour le bilig ?', '200-230°C', '100°C', '300°C', '150°C', 'A', 'food', true),
  ('Le ''pâté Hénaff'' est composé de ?', 'Porc et sel', 'Porc, sel, poivre, épices', 'Veau', 'Poulet', 'B', 'food', true),
  ('Quel est le slogan d''Hénaff ?', 'Tout est bon dans le Hénaff', 'Le pâté du marin', 'Pur cochon', 'Aucun officiel', 'A', 'food', true),
  ('Le ''galettoux'' est ?', 'Vendeur ambulant de galettes', 'Outil', 'Plat', 'Inventé pour la question', 'A', 'food', true),
  ('Quelle algue brune se cuisine en accompagnement ?', 'Spaghetti de mer', 'Nori (japonaise)', 'Spiruline', 'Chlorelle', 'A', 'food', true),
  ('Quel est le record du monde de la plus grande crêpe ?', 'Environ 15 m', '5 m', '30 m', '100 m', 'A', 'food', true),
  ('La fête de la crêpe à Gourin (Morbihan) date de ?', 'Années 80', 'Années 50', 'Années 2000', 'Années 60', 'A', 'food', true),
  ('Quelle sauce sucrée bretonne est très courante ?', 'Caramel beurre salé', 'Crème anglaise', 'Sabayon', 'Toutes possibles', 'A', 'food', true),
  ('Le ''gâteau au chocolat breton'' est souvent à base de ?', 'Beurre salé', 'Crème', 'Lait concentré', 'Huile', 'A', 'food', true),
  ('La ''galette de blé noir'' aux Saint-Jacques est ?', 'Plat festif breton', 'Plat industriel', 'Plat asiatique', 'Plat alsacien', 'A', 'food', true),
  ('Quel chef breton étoilé est célèbre à Locronan ?', 'Olivier Bellin (à Plomodiern)', 'Anne-Sophie Pic', 'Paul Bocuse', 'Yannick Alléno', 'A', 'food', true),
  ('Olivier Bellin est chef de ?', 'L''Auberge des Glazicks', 'Le Bristol', 'Le Meurice', 'L''Astrance', 'A', 'food', true),
  ('Quel restaurant 3* est à Plomodiern (Finistère) ?', 'L''Auberge des Glazicks', 'L''Atelier Crenn', 'Le Cinq', 'Mirazur', 'A', 'food', true),
  ('La cuisine bretonne mise sur ?', 'Produits locaux et de la mer', 'Importations', 'Surgelés', 'Industriel', 'A', 'food', true),
  ('Le ''kig sall'' se traduit par ?', 'Viande salée', 'Viande fumée', 'Viande crue', 'Viande séchée', 'A', 'food', true),
  ('Le ''tripoux'' est-il breton ?', 'Non, Auvergne', 'Oui', 'Normand', 'Vendéen', 'A', 'food', true),
  ('Le ''jambon de Bayonne'' est-il breton ?', 'Non, Sud-Ouest', 'Oui', 'Normand', 'Breton du Sud', 'A', 'food', true),
  ('Le ''jambon blanc breton'' est souvent ?', 'À l''os, cuit au torchon', 'Industriel', 'Fumé', 'Cru', 'A', 'food', true),
  ('Quel fromage breton AOP existe-t-il ?', 'Aucun AOP local strict, le curé nantais existe', 'Camembert breton', 'Comté breton', 'Roquefort breton', 'A', 'food', true),
  ('Quel atelier fromager est connu en Bretagne ?', 'La Pie Noir Henri Voisin', 'Bordier (beurre)', 'Tous', 'Aucun', 'A', 'food', true),
  ('La ''crêpe complète'' est aussi appelée ?', 'Galette complète', 'Galette de blé noir complète', 'Tous deux', 'Galette mixte', 'C', 'food', true),
  ('Quel jus accompagne classiquement le sarrasin ?', 'Cidre', 'Bière', 'Vin blanc', 'Eau plate', 'A', 'food', true),
  ('Quelle est la couleur du sarrasin moulu ?', 'Gris-beige', 'Blanc pur', 'Brun foncé', 'Noir', 'A', 'food', true),
  ('Le sarrasin pousse en combien de mois (env.) ?', '3-4 mois', '1 an', '6 mois', '2 ans', 'A', 'food', true),
  ('Quel insecte aide la pollinisation du sarrasin ?', 'Abeille (miel de sarrasin)', 'Mouche', 'Coccinelle', 'Aucun', 'A', 'food', true),
  ('Le ''miel de sarrasin'' est ?', 'Foncé, corsé', 'Clair, doux', 'Blanc, neutre', 'Vert, amer', 'A', 'food', true),
  ('Le ''miel de Bretagne'' est souvent ?', 'Toutes fleurs côtier', 'De lavande', 'D''acacia', 'De colza uniquement', 'A', 'food', true),
  ('Quel apiculteur breton est très connu ?', 'Aucun nom unique célèbre nationalement', 'Hédène (Loire)', 'Hediard (Paris)', 'Mariage (Paris)', 'A', 'food', true),
  ('Quel produit accompagne le ''far'' chaud ?', 'Crème fraîche ou rien', 'Glace', 'Caramel', 'Tous possibles', 'A', 'food', true),
  ('Quelle est la pâtisserie la plus calorique de Bretagne ?', 'Kouign-amann', 'Far', 'Quatre-quarts', 'Galette', 'A', 'food', true),
  ('Le kouign-amann a été qualifié par le NYT de ?', '''le plus gras de tous''', '''le plus exotique''', '''le moins sucré''', '''le plus simple''', 'A', 'food', true),
  ('Combien d''étapes de tour pour un kouign-amann ?', '2', '3-4', '10', '1', 'B', 'food', true),
  ('Le kouign-amann est souvent vendu ?', 'Individuel ou grand', 'Uniquement géant', 'Uniquement mini', 'En boîte sucrée', 'A', 'food', true),
  ('Quelle est la garniture la plus vendue en crêperie ?', 'Complète et sucre/beurre', 'Saumon', 'Caramel', 'Forestière', 'A', 'food', true),
  ('Le ''cidre brut'' contient ?', 'Très peu de sucre résiduel', 'Beaucoup de sucre', 'Pas d''alcool', 'Sucre ajouté', 'A', 'food', true),
  ('La ''pomme à cidre'' est ?', 'Plus tannique et acide', 'Sucrée comme dessert', 'Identique pomme à croquer', 'Toujours rouge', 'A', 'food', true),
  ('Combien d''années un pommier produit-il (env.) ?', 'Quelques années', '10 ans', 'Plusieurs décennies', 'Toujours', 'C', 'food', true),
  ('Quel verger breton est notable ?', 'Vergers du domaine de Kerfontaine etc.', 'Aucun', 'Plougastel pour pommes', 'Tous existent', 'A', 'food', true),
  ('Le cidre fermier breton se sert ?', 'Frais', 'Tiède', 'Bouillant', 'Glacé congelé', 'A', 'food', true),
  ('Quelle bière artisanale bretonne célèbre ?', 'Coreff, Lancelot, Mor Braz, Britt', 'Toutes existent', 'Aucune', 'Une seule', 'A', 'food', true),
  ('Quelle ville accueille la ''Brasserie de Bretagne'' ?', 'Concarneau / Trégunc', 'Brest', 'Quimper', 'Lorient', 'A', 'food', true),
  ('Quelle marque produit la ''Britt'' ?', 'Brasserie de Bretagne', 'Coreff', 'Lancelot', 'Sant Erwann', 'A', 'food', true),
  ('Dans quel département se trouve Mamers ?', 'Sarthe (72)', 'Orne (61)', 'Eure-et-Loir (28)', 'Loir-et-Cher', 'A', 'local', true),
  ('Mamers est sous-préfecture de ?', 'La Sarthe', 'L''Orne', 'Aucune', 'Eure-et-Loir', 'A', 'local', true),
  ('Quelle région administrative inclut Mamers ?', 'Pays de la Loire', 'Normandie', 'Centre-Val de Loire', 'Bretagne', 'A', 'local', true),
  ('Quelle région naturelle entoure Mamers ?', 'Le Perche', 'Le Maine', 'La Beauce', 'La Sologne', 'A', 'local', true),
  ('Mamers est-elle traversée par une rivière ?', 'Oui (la Dive)', 'Non', 'Oui (la Sarthe)', 'Oui (le Loir)', 'A', 'local', true),
  ('Quel est le nombre approximatif d''habitants à Mamers ?', '~5 000', '~50 000', '~500', '~100 000', 'A', 'local', true),
  ('Quel marché est traditionnel à Mamers ?', 'Marché du lundi', 'Marché du dimanche', 'Marché du jeudi', 'Aucun marché', 'A', 'local', true),
  ('Quelle ville voisine est célèbre pour son centre médiéval ?', 'Bellême', 'Le Mans', 'Alençon', 'Mortagne', 'A', 'local', true),
  ('Bellême est-elle dans le Perche ?', 'Oui', 'Non', 'À moitié', 'Inconnu', 'A', 'local', true),
  ('Quel parc naturel régional inclut le secteur ?', 'PNR du Perche', 'PNR de Normandie-Maine', 'Les deux selon zones', 'Aucun', 'C', 'local', true),
  ('Mamers est à environ combien de km du Mans ?', '~45 km', '~5 km', '~150 km', '~250 km', 'A', 'local', true),
  ('Quelle est la spécialité fromagère du Perche ?', 'Camembert / pâtes molles', 'Comté', 'Roquefort', 'Cantal', 'A', 'local', true),
  ('Quel cheval est emblématique du Perche ?', 'Le Percheron', 'Le Trait Breton', 'Le Comtois', 'L''Ardennais', 'A', 'local', true),
  ('Le Percheron est un cheval ?', 'De trait', 'De selle', 'De course', 'Poney', 'A', 'local', true),
  ('De quelle couleur est généralement le Percheron ?', 'Gris ou noir', 'Bai', 'Alezan', 'Pie', 'A', 'local', true),
  ('Quel fruit est célèbre dans le Perche ?', 'La pomme à cidre', 'La cerise', 'La fraise', 'L''abricot', 'A', 'local', true),
  ('Quelle boisson est typique du Perche ?', 'Cidre, poiré', 'Vin', 'Pastis', 'Bière', 'A', 'local', true),
  ('Le poiré est fait avec ?', 'Des poires', 'Des pommes', 'Des raisins', 'Des prunes', 'A', 'local', true),
  ('Quelle ville voisine est célèbre pour son vieux centre médiéval ?', 'Mortagne-au-Perche', 'Le Mans', 'Alençon', 'La Ferté-Bernard', 'A', 'local', true),
  ('Mortagne-au-Perche est célèbre pour quel produit ?', 'Le boudin noir', 'La rillette', 'Le cidre', 'Le calva', 'A', 'local', true),
  ('Quelle foire célèbre le boudin à Mortagne ?', 'Foire au boudin', 'Foire au cochon', 'Foire au cidre', 'Foire au pain', 'A', 'local', true),
  ('Le Mans est célèbre pour ?', 'Les 24 Heures', 'Le carnaval', 'Les vendanges', 'Les fjords', 'A', 'local', true),
  ('La rillette est typique de ?', 'Le Mans', 'Tours', 'Saumur', 'Les deux Le Mans/Tours', 'D', 'local', true),
  ('Quelle est la spécialité douce d''Alençon ?', 'Dentelle', 'Bonbon', 'Sablé', 'Galette', 'A', 'local', true),
  ('Alençon est dans le département de ?', 'L''Orne', 'La Sarthe', 'La Mayenne', 'Le Maine-et-Loire', 'A', 'local', true),
  ('Le Perche est-il vallonné ?', 'Oui, paysage bocager', 'Plat', 'Montagneux', 'Désertique', 'A', 'local', true),
  ('Quelle activité touristique est typique du Perche ?', 'Randonnée et équitation', 'Plongée', 'Ski', 'Surf', 'A', 'local', true),
  ('La Sarthe est traversée par quelle rivière éponyme ?', 'La Sarthe', 'La Loire', 'L''Orne', 'L''Eure', 'A', 'local', true),
  ('Quel est le nom de la cathédrale du Mans ?', 'Saint-Julien', 'Notre-Dame', 'Saint-Pierre', 'Saint-Étienne', 'A', 'local', true),
  ('Quel mur antique entoure le vieux Mans ?', 'Enceinte gallo-romaine', 'Mur médiéval', 'Rempart royal', 'Aucun', 'A', 'local', true),
  ('Quel film a été tourné dans le vieux Mans ?', 'Cyrano de Bergerac', 'Les Trois Mousquetaires', 'Les deux', 'Aucun', 'C', 'local', true),
  ('Mamers a un beffroi ?', 'Oui (église Saint-Nicolas)', 'Non', 'Démoli', 'Inconnu', 'A', 'local', true),
  ('Quelle église est emblématique à Mamers ?', 'Notre-Dame ou Saint-Nicolas', 'Saint-Pierre', 'Sainte-Anne', 'Saint-Yves', 'A', 'local', true),
  ('Quelle gare ferroviaire dessert Mamers ?', 'Gare de Mamers (TER)', 'Aucune', 'Gare TGV', 'Gare RER', 'A', 'local', true),
  ('Quel TER relie Mamers ?', 'Le Mans–Alençon (axes voisins)', 'Paris direct', 'Lyon direct', 'Marseille direct', 'A', 'local', true),
  ('Quel produit local est célèbre dans la Sarthe ?', 'Rillettes du Mans', 'Choucroute', 'Cassoulet', 'Aligot', 'A', 'local', true),
  ('La poule de Loué est de quel département ?', 'Sarthe', 'Mayenne', 'Maine-et-Loire', 'Orne', 'A', 'local', true),
  ('La poule de Loué est ?', 'Label Rouge', 'AOP', 'Bio uniquement', 'STG', 'A', 'local', true),
  ('Quelle célèbre course automobile a lieu près du Mans ?', '24 Heures du Mans', 'Grand Prix de France', 'Rallye de Monte-Carlo', 'Indy 500', 'A', 'local', true),
  ('Depuis quelle année se court Le Mans 24h ?', '1923', '1955', '1970', '2000', 'A', 'local', true),
  ('Quel circuit accueille les 24 Heures ?', 'Circuit de la Sarthe', 'Circuit Bugatti', 'Les deux', 'Magny-Cours', 'C', 'local', true),
  ('Quel motoriste est célèbre au Mans (Mulsanne) ?', 'Aucun motoriste, ligne droite', 'Honda', 'Ferrari', 'Tous', 'A', 'local', true),
  ('Quelle marque française a souvent gagné Le Mans ?', 'Peugeot', 'Renault', 'Citroën', 'Toutes ont participé', 'A', 'local', true),
  ('Quelle fête a lieu en automne à Mamers ?', 'La fête du cidre / foire', 'Carnaval', 'Fête de la mer', 'Fête des fleurs', 'A', 'local', true),
  ('Quel marché aux bestiaux historique avait lieu près de Mamers ?', 'Saint-Cosme/Mamers/Perche', 'Aucun', 'Saint-Tropez', 'Marseille', 'A', 'local', true),
  ('Le Perche se situe entre ?', 'Normandie, Maine, Beauce', 'Bretagne, Vendée', 'Alsace, Lorraine', 'Rhône, Alpes', 'A', 'local', true),
  ('La Trappe (bière trappiste) est à quelle distance de Mamers ?', 'Proche (Soligny-la-Trappe)', 'À 1000 km', 'Aucune trappe', 'À Brest', 'A', 'local', true),
  ('Quelle abbaye est près de Mamers ?', 'Abbaye de la Trappe', 'Mont-Saint-Michel', 'Saint-Wandrille', 'Aucune', 'A', 'local', true),
  ('Quelle bière est produite à la Trappe en Normandie ?', 'La Trappe (NL) / pas Trappe-Soligny brassée seule', 'Chimay', 'Westmalle', 'La Trappe Soligny relancée récemment', 'D', 'local', true),
  ('Quelle marque de cidre est très connue dans l''Orne ?', 'Cidres du Perche / Lemorton', 'Loïc Raison', 'Kerisac', 'Toutes commercialisées', 'A', 'local', true),
  ('Quelle distillerie de Calvados est dans l''Orne ?', 'Calvados Domfrontais (poire)', 'Pays d''Auge', 'Les deux dans Normandie', 'Aucune', 'C', 'local', true),
  ('Le Calvados Domfrontais est-il à base de poire ?', 'Oui en partie', 'Non, pommes uniquement', 'Non, prunes', 'Non, raisins', 'A', 'local', true),
  ('Quelle ville est jumelée avec Mamers (notable) ?', 'Cervia (Italie)', 'Aucune', 'Bristol', 'Madrid', 'A', 'local', true),
  ('Quel est le nom de la halle de Mamers ?', 'Halles couvertes du XIXe', 'Halles Baltard', 'Halles modernes', 'Aucune halle', 'A', 'local', true),
  ('Quelle école hôtelière est près de Mamers ?', 'Lycée Yvonne Le Tac (non)/aucune célèbre', 'Aucune réputation nationale', 'Ferrandi', 'Tain l''Hermitage', 'B', 'local', true),
  ('Quel sport est très pratiqué au Perche ?', 'Équitation', 'Surf', 'Ski', 'Plongée', 'A', 'local', true),
  ('Quel haras national est dans la région ?', 'Haras du Pin', 'Haras de Saumur', 'Haras de Lyon', 'Haras de Pompadour', 'A', 'local', true),
  ('Le Haras du Pin est appelé ?', 'Le Versailles du cheval', 'Le palais équin', 'Aucun surnom', 'Le palais royal', 'A', 'local', true),
  ('Le Haras du Pin est dans quel département ?', 'L''Orne', 'La Sarthe', 'Le Calvados', 'L''Eure', 'A', 'local', true),
  ('Quelle ville accueille le concours hippique de Mamers ?', 'Mamers (haras local)', 'Aucune', 'Le Mans', 'Alençon', 'A', 'local', true),
  ('Quel artisanat est typique du Perche ?', 'Poterie, vannerie, ferronnerie', 'Soierie', 'Verrerie soufflée', 'Tannage', 'A', 'local', true),
  ('Quel village du Perche est classé ''plus beau village'' ?', 'Saint-Céneri-le-Gérei (proche)', 'Aucun', 'Locronan', 'Conques', 'A', 'local', true),
  ('Quelle forêt domaniale est près de Mamers ?', 'Forêt de Perseigne', 'Forêt de Brocéliande', 'Forêt de Tronçais', 'Forêt de Fontainebleau', 'A', 'local', true),
  ('La forêt de Perseigne abrite ?', 'Cerfs, sangliers, chevreuils', 'Loups', 'Ours', 'Renne', 'A', 'local', true),
  ('Quel animal était autrefois chassé à courre dans le Perche ?', 'Cerf et sanglier', 'Renard uniquement', 'Aigle', 'Ours', 'A', 'local', true),
  ('Quelle activité est interdite en forêt de Perseigne ?', 'Feu de camp', 'Marche', 'VTT', 'Cueillette raisonnable', 'A', 'local', true),
  ('Quel est le nom du PNR du Perche ?', 'Parc naturel régional du Perche', 'PNR du Maine', 'PNR Normandie-Maine', 'Aucun', 'A', 'local', true),
  ('Le PNR du Perche couvre quels départements ?', 'Orne et Eure-et-Loir', 'Orne et Sarthe', 'Sarthe seul', 'Mayenne seul', 'A', 'local', true),
  ('Quelle ville est appelée ''capitale du Perche'' ?', 'Mortagne-au-Perche', 'Mamers', 'Bellême', 'Nogent-le-Rotrou', 'A', 'local', true),
  ('Nogent-le-Rotrou est dans quel département ?', 'Eure-et-Loir', 'Sarthe', 'Orne', 'Loir-et-Cher', 'A', 'local', true),
  ('Quel château surplombe Nogent-le-Rotrou ?', 'Château Saint-Jean', 'Château de Bellême', 'Château de Mamers', 'Aucun', 'A', 'local', true),
  ('Quelle pomme du Perche est célèbre ?', 'Reinette d''Orléans, Domaines locaux', 'Granny', 'Pink Lady', 'Royal Gala', 'A', 'local', true),
  ('Le ''cidre du Perche'' bénéficie de ?', 'IGP', 'AOP', 'Aucun label', 'Label rouge', 'A', 'local', true),
  ('Quelle ville sarthoise est célèbre pour ses fleurs ?', 'Aucune nationalement, Yvré-l''Évêque local', 'Le Mans', 'Mamers', 'Sablé-sur-Sarthe', 'A', 'local', true),
  ('Le marbre ''rouge royal'' est extrait à ?', 'Sablé-sur-Sarthe', 'Le Mans', 'Mamers', 'La Flèche', 'A', 'local', true),
  ('La Flèche abrite ?', 'Le Prytanée militaire', 'Une cathédrale', 'Une plage', 'Une forêt vierge', 'A', 'local', true),
  ('Quel zoo célèbre est dans la Sarthe ?', 'Zoo de la Flèche', 'Zoo de Beauval', 'Zoo de Vincennes', 'Zoo de Doué', 'A', 'local', true),
  ('Le zoo de la Flèche est connu pour ?', 'Les ours polaires, tigres', 'Les pingouins seulement', 'Les pandas', 'Aucun animal', 'A', 'local', true),
  ('Quelle célèbre émission TV s''y tournait ?', 'Une saison au zoo', 'Tournez manège', 'Fort Boyard', 'Pékin Express', 'A', 'local', true),
  ('Quelle ville sarthoise est jumelée avec Paderborn ?', 'Le Mans', 'Mamers', 'La Flèche', 'Sablé', 'A', 'local', true),
  ('Quel pont historique est au Mans ?', 'Pont Yssoir', 'Pont d''Iéna', 'Pont Neuf', 'Aucun', 'A', 'local', true),
  ('Quel fleuve traverse la ville du Mans ?', 'La Sarthe (et l''Huisne)', 'La Loire', 'L''Eure', 'L''Orne', 'A', 'local', true),
  ('La rivière Huisne est un affluent de ?', 'La Sarthe', 'La Loire', 'L''Eure', 'L''Orne', 'A', 'local', true),
  ('Quelle abbaye troglodyte est dans la Sarthe ?', 'Aucune célèbre, plutôt L''Épau', 'Solesmes', 'Toutes deux célèbres', 'Aucune', 'B', 'local', true),
  ('L''abbaye Saint-Pierre de Solesmes est connue pour ?', 'Le chant grégorien', 'L''art roman', 'Les vitraux', 'Tous', 'A', 'local', true),
  ('Solesmes se trouve dans quel département ?', 'Sarthe', 'Mayenne', 'Eure-et-Loir', 'Maine-et-Loire', 'A', 'local', true),
  ('Quelle ville sarthoise est célèbre pour ses sablés ?', 'Sablé-sur-Sarthe', 'Mamers', 'Le Mans', 'La Flèche', 'A', 'local', true),
  ('Le sablé est ?', 'Un biscuit beurré', 'Un pain', 'Une crêpe', 'Un fromage', 'A', 'local', true),
  ('Quel fromage est typique de la Mayenne voisine ?', 'Port-Salut', 'Comté', 'Bleu', 'Roquefort', 'A', 'local', true),
  ('Quel monument est emblématique du Mans ?', 'Plantagenêt (vieux Mans)', 'Pyramide', 'Vieux port', 'Beffroi', 'A', 'local', true),
  ('Quelle reine célèbre est née au Mans ?', 'Bérengère de Navarre y est inhumée', 'Aliénor d''Aquitaine', 'Anne de Bretagne', 'Aucune', 'A', 'local', true),
  ('Quel roi est né au Mans ?', 'Henri II Plantagenêt', 'Louis XIV', 'Charlemagne', 'Aucun', 'A', 'local', true),
  ('Quelle marque automobile fut fondée au Mans ?', 'Bollée (premières voitures)', 'Renault', 'Peugeot', 'Aucune', 'A', 'local', true),
  ('Amédée Bollée a inventé ?', 'Une voiture à vapeur (L''Obéissante)', 'Le moteur diesel', 'Le pneu', 'Le volant', 'A', 'local', true),
  ('Quel fabricant d''assurance est basé au Mans ?', 'MMA / Covéa', 'AXA', 'Allianz', 'Aucun', 'A', 'local', true),
  ('Quelle université est dans la Sarthe ?', 'Le Mans Université', 'Aucune', 'Sorbonne', 'Sciences Po', 'A', 'local', true),
  ('Quelle station thermale est dans l''Orne (proche) ?', 'Bagnoles-de-l''Orne', 'Vichy', 'Évian', 'Vittel', 'A', 'local', true),
  ('Quel département voisin de la Sarthe au nord ?', 'Orne', 'Mayenne', 'Eure-et-Loir', 'Indre-et-Loire', 'A', 'local', true),
  ('Quel département au sud de la Sarthe ?', 'Maine-et-Loire', 'Mayenne', 'Indre-et-Loire', 'Loir-et-Cher', 'A', 'local', true),
  ('Quel département à l''ouest de la Sarthe ?', 'Mayenne', 'Orne', 'Indre-et-Loire', 'Loir-et-Cher', 'A', 'local', true),
  ('Quel département à l''est de la Sarthe ?', 'Eure-et-Loir et Loir-et-Cher', 'Indre-et-Loire', 'Vienne', 'Eure', 'A', 'local', true),
  ('Quelle est la préfecture de la Sarthe ?', 'Le Mans', 'La Flèche', 'Mamers', 'Sablé', 'A', 'local', true),
  ('Quel est le code postal de Mamers ?', '72600', '61000', '72000', '72100', 'A', 'local', true),
  ('Quel département a Alençon comme préfecture ?', 'Orne', 'Sarthe', 'Mayenne', 'Calvados', 'A', 'local', true);