// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function getRequiredEnv(name: "VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY"): string {
  const value = import.meta.env[name];
  if (!value || typeof value !== "string") {
    throw new Error(`[supabase] Missing environment variable: ${name}`);
  }
  return value;
}

// Safe storage: avoids crashes in SSR/tests or restricted environments
function getSafeStorage(): Storage | undefined {
  try {
    if (typeof window === "undefined") return undefined;
    if (!("localStorage" in window)) return undefined;

    // Test write (can throw in private mode / strict settings)
    const key = "__supabase_storage_test__";
    window.localStorage.setItem(key, "1");
    window.localStorage.removeItem(key);

    return window.localStorage;
  } catch {
    return undefined;
  }
}

const SUPABASE_URL = getRequiredEnv("VITE_SUPABASE_URL");
const SUPABASE_PUBLISHABLE_KEY = getRequiredEnv("VITE_SUPABASE_PUBLISHABLE_KEY");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // Safe default for OAuth redirect flows (Google, etc.)
    detectSessionInUrl: true,
  },
  // Optional but safe if you’re always using public schema:
  // db: { schema: "public" },
});
